version: '3.8'

services:
  trump-tracker:
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./daily_exports:/app/daily_exports
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - trump-tracker
    restart: unless-stopped 